name: 'Terraform'

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0  # Update with the desired Terraform version

      - name: Configure AWS credentials
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

      - name: Initialize Terraform
        run: terraform init -backend-config=terraform/backend.tfvars

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Output EC2 public IP
        run: echo "EC2 Public IP: ${{ steps.apply.outputs.outputs.instance_public_ip }}"
